feat: use isPossible instead of isValid to relax phone number validation
opengovsg/FormSG pull request #1317
Opened 2021-03-08 12:21 UTC by tshuli

## Problem

Closes #1257

## Solution
Relaxes phone number validation by using isPossible() method instead of isValid() method.

From the [docs](https://www.npmjs.com/package/libphonenumber-js):
```
isPossible(): boolean
Checks if the phone number is "possible". 
Only checks the phone number length, doesn't check the actual phone number digits against any regular expressions.

isValid(): boolean
Checks if the phone number is "valid". 
First checks the phone number length and then checks the phone number digits against all available regular expressions.
``` 

## Tests
- [ ] Create verified SMS field. Check that SMS can still be sent and received for valid Singapore number.

2021-03-08 13:20 UTC, liangyuanruo commented on src/app/models/user.server.model.ts
> +            return phoneNumber.isPossible()
does the issue to address include the form admin?

2021-03-08 13:22 UTC, liangyuanruo approved these changes
please confirm with @syan-syan on whether the issue is scoped to form submissions only, or is the admin's contact included. otherwise lgtm!

2021-03-09 07:58 UTC, liangyuanruo requested changes
Clarified with @syan-syan that there should be no change to the form admin's contact details.

2021-03-11 01:48 UTC, tshuli commented
@liangyuanruo restored isValid check for admin numbers, for approval

2021-03-16 01:30 UTC, liangyuanruo approved these changes

2021-03-16 01:31 UTC, merged