refactor: Migrate 3 more filters to handleEncryptedSubmission
opengovsg/FormSG pull request #1420
Opened 2021-03-21 21:34 UTC by frankchn

Problem
Part of the set of pull requests that addresses #149

Solution
Migrate `validateAndProcessEncryptSubmission`, `isSpcpAuthenticated`, and `verifyMyInfoVals` to `handleEncryptedSubmission`.

2021-03-22 08:08 UTC, liangyuanruo requested changes
Code looks good, but need to migrate tests

2021-03-24 08:43 UTC, frankchn commented
@liangyuanruo Tests are fixed, PTAL again :)

2021-03-26 07:22 UTC, liangyuanruo commented on src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts
> +  delete (req.body as SetOptional<EncryptSubmissionBody, 'responses'>).responses
Could you help to add a TODO that this segment of code should eventually be refactored in #1104 ?

2021-03-26 07:25 UTC, liangyuanruo commented on src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts
> +    res.locals.userInfo = spcpResult.value.userInfo
To also note that long-range dependencies via `res.locals` should eventually be removed as part of #149 (which this PR is tackling).

2021-03-26 07:25 UTC, liangyuanruo commented on src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts
> +  const uinFin = (res as ResWithUinFin<typeof res>).locals.uinFin
To also note that long-range dependencies via res.locals should eventually be removed as part of #149 (which this PR is tackling).

2021-03-26 07:27 UTC, liangyuanruo commented on src/app/modules/submission/encrypt-submission/encrypt-submission.controller.ts
> +    )
Could you help to see (maybe in a future PR) whether this can be rolled into a single service?

2021-03-26 07:29 UTC, liangyuanruo approved these changes

2021-03-28 03:02 UTC, merged