ref(corppass-ui): make ui changes for corppass
opengovsg/FormSG pull request #1533
Opened 2021-03-31 08:15 UTC by orbitalsqwib

## Problem

Make appropriate UI updates to FormSG to prepare for Corppass migration.

Closes #1446

## Solution

**Features**:

- update copy for ui
- update all mentions of singpass and corppass to use new casing
- make necessary frontend changes for corporate singpass button
- add tooltip beside corppass option in settings > enable authentication

## Before & After Screenshots

**BEFORE**:
<img width="1792" alt="Screenshot 2021-03-31 at 4 08 56 PM" src="https://user-images.githubusercontent.com/21305518/113112465-c6256f80-923b-11eb-9869-59b768c256ee.png">
<img width="1792" alt="Screenshot 2021-03-31 at 4 10 19 PM" src="https://user-images.githubusercontent.com/21305518/113112485-c9b8f680-923b-11eb-9122-b58a55134fc7.png">
<img width="1792" alt="Screenshot 2021-03-31 at 4 09 51 PM" src="https://user-images.githubusercontent.com/21305518/113112489-cb82ba00-923b-11eb-9c6a-ce8c37e86161.png">

**AFTER**:
<img width="1792" alt="Screenshot 2021-03-31 at 3 31 36 PM" src="https://user-images.githubusercontent.com/21305518/113112551-df2e2080-923b-11eb-85ed-958988d8922e.png">
<img width="1792" alt="Screenshot 2021-03-31 at 3 31 51 PM" src="https://user-images.githubusercontent.com/21305518/113112525-d76e7c00-923b-11eb-8d85-cbbb22def783.png">
<img width="1792" alt="Screenshot 2021-03-31 at 3 32 25 PM" src="https://user-images.githubusercontent.com/21305518/113112529-d9383f80-923b-11eb-8760-75b7f1fb70ed.png">
<img width="1792" alt="Screenshot 2021-03-31 at 3 22 41 PM" src="https://user-images.githubusercontent.com/21305518/113112544-dd645d00-923b-11eb-8c8c-43466a797af3.png">
<img width="1138" alt="Screenshot 2021-03-31 at 3 24 11 PM" src="https://user-images.githubusercontent.com/21305518/113112546-ddfcf380-923b-11eb-9df7-5d7ed7c90478.png">
<img width="1792" alt="Screenshot 2021-03-31 at 3 22 08 PM" src="https://user-images.githubusercontent.com/21305518/113112540-dc333000-923b-11eb-8d45-c216803bf078.png">
<img width="1792" alt="Screenshot 2021-03-31 at 3 31 01 PM" src="https://user-images.githubusercontent.com/21305518/113112548-de958a00-923b-11eb-81d2-9926d988be56.png">

## Tests

- update e2e tests for new changes

2021-03-31 08:17 UTC, mantariksh commented
sadly GitHub's "Semantic Pull Request" check doesn't accept "ref" as a semantic commit prefix, as "ref" is just an innovation we came up with to shorten "refactor" haha. I think the check will pass if you change "ref" in your commit and PR title to "refactor".

2021-03-31 08:27 UTC, karrui requested changes
some comments

2021-03-31 08:27 UTC, karrui commented on CHANGELOG.md
> +- feat: revert custom code for Corppass cloud migration [`#1476`](https://github.com/opengovsg/FormSG/pull/1476)
Might want to revert the casings here, since this is a changelog (and will get automatically updated the next time we release anyways)

2021-03-31 08:27 UTC, karrui commented on scripts/20191212_dangling-key-cleanup/delete-keys.js
> +    Corppass: 1,
might want to revert this, this script is kept here for historical purposes and should not be editted

2021-03-31 08:27 UTC, karrui commented on scripts/20200923_unused-key-cleanup/delete-isSingPassAuthenticated-key.js
> +  .find({ 'isSingpassAuthenticated': { $exists: true } })
Same for this file

2021-03-31 08:27 UTC, karrui commented on scripts/20210224_myinfo-authtype/myinfo-authtype.js
> +// A: Number of Singpass forms
Same for this file, even though it is just a comment

2021-03-31 08:27 UTC, karrui commented on scripts/20210224_myinfo-authtype/myinfo-authtype.rollback.js
> +// B: Number of Singpass authType forms
ditto

2021-03-31 08:27 UTC, karrui commented on src/public/modules/core/resources/landing-examples.js
> +      'Our sincere thanks to GovTech for creating FormSG along with the macro script, data collation tool and Singpass verification. This is very useful on so many levels. We use it to collect data f
Maybe don't change this, since this is a quote from someone else

2021-03-31 08:27 UTC, karrui commented on src/types/field/fieldTypes.ts
> +  SpNric = 'Singpass Validated NRIC',
@mantariksh correct me if i'm wrong, this will affect RPA right? Since email JSONs will change their field titles. 

@syan-syan fyi

2021-03-31 08:29 UTC, orbitalsqwib commented
noted that there are a lot of undesirable changes for the singpass/corppass casing update, will look into it again

2021-03-31 08:32 UTC, syan-syan commented
sorry i should 100% have clarified this earlier - change Singpass and Corppass casing **only on the frontend but not in any code that would change casing on response data passed to users**. this is because it will affect RPA as @karrui correctly pointed out.

2021-03-31 08:33 UTC, orbitalsqwib commented
alright, making appropriate changes now

2021-03-31 09:45 UTC, orbitalsqwib commented
@syan-syan should the form preview also include the change to add "Logged in as corporate user" to the colored area?

2021-03-31 10:18 UTC, syan-syan commented
> @syan-syan should the form preview also include the change to add "Logged in as corporate user" to the colored area?

Yes to the coloured area, screenshot above is correct.

2021-04-01 04:10 UTC, mantariksh requested changes
could you remove all the changes related to the global change of singpass/corppass casing, as well as all changes in unrelated files? only leave in the files related to the actual UI changes. we try our best to limit PRs to only the necessary changes to make them easier to review. if you need to do a global rename/lint, you can do it in a separate PR where the rename/lint is the _only_ change, so we can be sure that no code logic is changing.

2021-04-05 03:05 UTC, mantariksh requested changes
if you look at the files changed, the majority of changes are still from the global casing change. could you revert all those pls? and as mentioned earlier, if necessary you can do a global rename in a separate PR

2021-04-05 05:36 UTC, mantariksh reviewed
the padding on the "login with singpass (corporate)" button is a little narrow, so we should either increase that or change the button to two lines by enforcing a max width. lgtm otherwise, well done for making the changes so quickly!

2021-04-05 07:21 UTC, mantariksh approved these changes
lgtm! before you merge this, could you add in some manual tests in your PR under the "Tests" section for us to check that everything looks correct on staging before release? can look at #1440 for an example.
e.g. "Check that tooltip appears next to "Corppass" in Settings tab"

2021-04-05 08:29 UTC, karrui approved these changes
lgtm

2021-04-05 08:33 UTC, merged