feat: store only user ID in session
opengovsg/FormSG pull request #1849
Opened 2021-05-10 11:44 UTC by jia1

Closes #212

2021-06-01 02:53 UTC, karrui approved these changes
lgtm

2021-06-01 02:54 UTC, karrui requested changes
actually, in `src/app/loaders/express/logging.ts`, we have a getter for session.user._id for logging and that may break if we don't update that too

2021-06-01 02:56 UTC, karrui requested changes

2021-06-01 02:56 UTC, karrui commented on src/types/vendor/express.d.ts
> +      user?: IUserSchema['_id']
this should look like 

```ts
user?: {
  _id: IUserSchema['_id']
}
```

2021-06-01 02:56 UTC, karrui commented on src/types/vendor/express.d.ts
> +      user: IUserSchema['_id']
Same here

2021-06-07 02:10 UTC, karrui reviewed
should be ok now, just need to fix the build error (remove the user.email call (since session doesn't contain the full user anymore) and replace it with _id i guess))

also search the codebase for instances of `TODO(#212)` and remove them! :D

2021-06-08 10:36 UTC, jia1 commented
@karrui Do you mean the line containing: `message: Successfully logged in user ${user._id},`? Reference to `.email` was removed but pipeline still fails. [Travis build](https://travis-ci.com/github/opengovsg/FormSG/builds/228306260) gives me an empty screen.

2021-06-09 02:39 UTC, karrui commented
> @karrui Do you mean the line containing: `message: Successfully logged in user ${user._id},`? Reference to `.email` was removed but pipeline still fails. [Travis build](https://travis-ci.com/github/opengovsg/FormSG/builds/228306260) gives me an empty screen.

I've fixed it, can check out my commit for more info!

2021-06-09 06:23 UTC, karrui approved these changes
lgtm

2021-06-09 06:24 UTC, merged