feat: display different e-service placeholder text for singpass and corpass
opengovsg/FormSG pull request #1968
Opened 2021-05-25 05:20 UTC by chowyiyin

This PR changes the placeholder text for entering e-service IDs. 

Closes #1675

## Tests
- [ ] Change authentication method to Singpass and Singpass(MyInfo). Placeholder text should show "Enter Singpass e-service ID".
- [ ] Change authentication method to Singpass(Corporate). Placeholder text should show "Enter Corppass e-service ID"

2021-05-25 09:04 UTC, mantariksh requested changes
could you include some screenshots (can be from your local dev environment) in the PR? we usually do this for frontend changes so the reviewer has additional reassurance that it works

2021-05-25 09:04 UTC, mantariksh commented on src/public/modules/forms/admin/directiveViews/settings-form.client.view.html
> +                    placeholder="{{ ['SP', 'MyInfo'].includes(type.val) && 'Enter Singpass e-service ID' || 'Enter Corppass e-service ID' }}"
a [ternary operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator) would probably be more appropriate for this case

2021-05-25 10:53 UTC, mantariksh approved these changes

2021-05-27 02:01 UTC, merged

2021-06-01 06:18 UTC, yong-jie commented
+1 thanks for the screenshots, was helpful when doing release checks since it wasnt clear what the placeholders referred to