refactor(proxy): do not override X-Forwarded-Proto headers
opengovsg/FormSG pull request #304
Opened 2020-09-09 04:15 UTC by liangyuanruo

Closes https://github.com/datagovsg/formsg-private/issues/33

2020-09-09 07:48 UTC, arshadali172 commented on src/loaders/express/index.ts
> +      app.set('trust proxy', true)
isn't it better to explicitly set the number of hops as 1?

2020-09-09 07:50 UTC, arshadali172 requested changes
isn't it better to explicitly set the number of hops as 1?

2020-09-09 08:07 UTC, liangyuanruo commented
> isn't it better to explicitly set the number of hops as 1?

It is simpler to set it to `true` to accommodate the general case where the left-most [X-Forwarded-For](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For) header is the client IP address, since we do not need to make assumptions on the number of proxies for open source users. It is also the [first setting](https://expressjs.com/en/guide/behind-proxies.html) employed in Express.

2020-09-10 02:26 UTC, arshadali172 approved these changes

2020-09-10 02:27 UTC, merged