wip: Refactor/errors server controller
opengovsg/FormSG pull request #327
Opened 2020-09-17 06:02 UTC by shuli-ogp

wip

2020-09-18 17:14 UTC, karrui requested changes
Some changes requested, with the main one being to change it to a pure utility file. 

Please try to think of ways to improve the code too when you are refactoring instead of plainly converting JS to TS code! The main point we are doing this is to reduce tech debt/legacy code after all :D

2020-09-18 17:14 UTC, karrui commented on src/app/controllers/errors.server.controller.ts
> +export function getMongoErrorMessage(err?: IMongoError | string): string {
This whole function seems like it needs a good refactor, maybe we should try to clean up the function?

I don't think we should create the `IMongoError` interface when we already have the typings of the possible errors:

```ts
import { MongoError } from 'mongodb'
import { Error as MongooseError } from 'mongoose'

...
export const getMongoErrorMessage = (
  err?: MongoError | MongooseError | string,
): string => { ... }
```

2020-09-18 17:14 UTC, karrui commented on src/app/controllers/errors.server.controller.ts
> +export function getMongoErrorMessage(err?: IMongoError | string): string {
Suggested refactor:

```ts
export const getMongoErrorMessage = (
  err?: MongoError | MongooseError | string,
): string => {
  if (!err) {
    return ''
  }

  // Handle base Mongo engine errors.
  if (err instanceof MongoError) {
    switch (err.code) {
      case 10334: // BSONObj size invalid error
        return 'Your form is too large to be supported by the system.'
      default:
        return defaultErrorMessage
    }
  }

  // Handle mongoose errors.
  if (err instanceof MongooseError.ValidationError) {
    // Join all error messages into a single message if available.
    const joinedMessage = Object.values(err.errors)
      .map((err) => err.message)
      .join(', ')

    return joinedMessage ?? err.message ?? defaultErrorMessage
  }

  if (err instanceof MongooseError) {
    return err.message ?? defaultErrorMessage
  }

  return err ?? defaultErrorMessage
}
```

2020-09-18 17:14 UTC, karrui commented on src/types/error.ts
> +export interface IMongoError {
Unneeded, as explained above

2020-09-18 17:14 UTC, karrui commented on tests/unit/backend/controllers/errors.server.controller.spec.ts
> -describe('Errors Controller', () => {
Remember to update tests

2020-09-18 17:14 UTC, karrui commented on src/app/controllers/errors.server.controller.ts
> +const mongoDuplicateKeyError = function (err: IMongoError): string {
We can also keep it in if you want, but I'm not a fan of this weird error message interpolation.

2020-10-05 02:17 UTC, karrui commented
Any updates on this PR?

2020-10-09 02:04 UTC, shuli-ogp commented
Closing first to deprioritise, will pick up again after helium

2020-10-09 02:04 UTC, closed without merging