fix: add additional startsWith('@') check when validating domain
opengovsg/FormSG pull request #487
Opened 2020-10-19 09:27 UTC by karrui

## Problem

This PR adds an additional check for the allowed domains entered by the user to enforce starting with an '@' symbol. This prevents a form admin from adding a complete email address such as `test@example.com` into the allowed domain field.

Related to https://github.com/datagovsg/formsg-private/issues/53

## Solution

**Bug Fixes**:

- fix: add additional startsWith('@') check when validating domain

## Before & After Screenshots

**BEFORE**:
Allows full email domains
![Screenshot 2020-10-19 at 5 26 32 PM](https://user-images.githubusercontent.com/22133008/96426767-3d3bee00-1230-11eb-8842-4fa3b0058715.png)

**AFTER**:
Prevents full email addresses
![Screenshot 2020-10-19 at 3 51 58 PM](https://user-images.githubusercontent.com/22133008/96426703-2b5a4b00-1230-11eb-9690-3f5258af59f5.png)

2020-10-19 09:36 UTC, liangyuanruo requested changes
write a script to check whether the current database state is consistent with this change. otherwise, some admins may not be able to save their form.

2020-10-19 09:39 UTC, karrui commented
> write a script to check whether the current database state is consistent with this change. otherwise, some admins may not be able to save their form.

I've done a check, at of this instance the only malformed emails are testing domains by me and @syan-syan

2020-10-19 09:51 UTC, shuli-ogp approved these changes
lgtm!

2020-10-20 01:53 UTC, mantariksh reviewed
suggesting changing the error copy to "You may have duplicate or invalid email domains. Please check that all the domains start with @."

2020-10-20 02:12 UTC, liangyuanruo approved these changes
Ok

2020-10-20 02:32 UTC, merged