refactor: move logic for validateEncryptSubmission to utility
opengovsg/FormSG pull request #627
Opened 2020-11-12 13:37 UTC by tshuli

2020-11-12 13:38 UTC, tshuli commented
@karrui thanks for discussing earlier today, could I trouble you to take a look to see if this approach is roughly correct? :)

will clean up / write tests and work on submissions thereafter since you are refactoring the rest of encrypt-submissions

2020-11-13 01:39 UTC, karrui requested changes
I think the things you've refactored out as utilities actually belong in the domain of the controller and does not need to be extracted.

I think what you can do is to convert the utility functions currently being used into neverthrown functions so you don't need to wrap them in a try catch block.

2020-11-13 01:39 UTC, karrui commented on src/app/utils/encrypt-submission.ts
> +export const isValidEncryptSubmission = (req: Request): boolean => {
I don't think we need to create the `isValidEncryptSubmission` function, can't we use the `checkIsEncryptedEncoding` function directly?

I think we can update the `checkIsEncryptedEncoding` function into a neverthrown function instead.

2020-11-13 01:39 UTC, karrui commented on src/app/utils/encrypt-submission.ts
> +export const isValidEncryptSubmission = (req: Request): boolean => {
Utility functions should also not need to be aware of other layers, in this case this function needs to know about `req` from the controller layer, which is not what we want

2020-11-13 01:39 UTC, karrui commented on src/app/utils/encrypt-submission.ts
> +export const processResponses = (req: Request): void => {
Same here. The argument for this function should not be `Request`, but scoped to the variable it is going to act on. In this case, this whole block seems to be the domain of the controller and does not need to be extracted.

Also strive to make utility functions [pure](https://medium.com/javascript-scene/master-the-javascript-interview-what-is-a-pure-function-d1c076bec976). In this function, we are assigning to `req.body.parsedResponses` as a side effect, which can be hard to realize

2020-11-15 08:00 UTC, tshuli commented
@karrui Thanks a lot! 
Will close this and open a PR for neverthrow refactoring

2020-11-15 08:00 UTC, closed without merging