fix: disable payment resume and duplicate modals in preview
opengovsg/FormSG pull request #6334
Opened 2023-05-16 04:29 UTC by foochifa

## Problem

Currently we show both the `FormPaymentResumeModal` and `DuplicatePaymentModal` in preview mode if the same browser or email is used in a public form submission.

This should be disabled when the admin is in preview mode

## Solution

Check if form is in preview mode before displaying the modals.

**Breaking Changes** 

- [ ] No - this PR is backwards compatible  

**Improvements**:

- Shifted `isPreview` from a prop in `FormFieldsContainer` and `FormEndPageContainer` to a context in `usePublicFormContext`. As `isPreview` should be static, it can be inserted as a global context without much performance consideration (from hooks updates etc)

## Before & After Screenshots

**BEFORE**:

![image](https://github.com/opengovsg/FormSG/assets/59867455/b48a8a01-95e0-4572-a6ad-7c1832fe1673)
![image](https://github.com/opengovsg/FormSG/assets/59867455/4dd8382d-59dd-4e6b-a828-b4687a717a47)

**AFTER**:

## Tests

2023-05-16 09:30 UTC, LinHuiqing requested changes
After the first payment is attempted on preview mode, subsequent payments attempted on preview mode will still show the modal.

2023-05-16 09:49 UTC, foochifa commented
Thanks @LinHuiqing for catching that! Have confirmed with @staceytan1998 that all modals should not be shown in preview [69a7234](https://github.com/opengovsg/FormSG/pull/6334/commits/69a723471503bb0b87da808d9f0938050d9a1367)

2023-05-17 00:49 UTC, timotheeg approved these changes
LGTM. Thanks ChiFa!

2023-05-17 01:38 UTC, LinHuiqing approved these changes
lgtm and tested! as mentioned, will open a separate issue for the ever-present white box for payment preview even when payment is not enabled

2023-05-17 02:12 UTC, merged