fix(mrf): design review results page
opengovsg/FormSG pull request #7220
Opened 2024-04-01 17:38 UTC by KenLSM

## Problem

Results
- align the values in the box
- Date & time displayed on thank you page and results should use last submission timing

**Breaking Changes** 
- No - this PR is backwards compatible  

## Before & After Screenshots
| Item | Before | After |
|--------|--------|--------|
| Results Metadata | <img width="1173" alt="Screenshot 2024-04-02 at 1 37 16 AM" src="https://github.com/opengovsg/FormSG/assets/12391617/570ad3be-3fde-4c93-b4d4-87c31506b062"> | <img width="990" alt="Screenshot 2024-04-02 at 12 41 37 AM" src="https://github.com/opengovsg/FormSG/assets/12391617/4bc1496d-8995-4bf9-92f3-df9344e565fc"> |

## Tests

2024-04-03 04:31 UTC, justynoh approved these changes

2024-04-03 04:31 UTC, justynoh commented on frontend/src/features/admin-form/responses/IndividualResponsePage/IndividualResponsePage.tsx
> +  children: string | ReactNode
nit: can remove `string` here

2024-04-03 04:31 UTC, justynoh commented on frontend/src/features/admin-form/responses/IndividualResponsePage/IndividualResponsePage.tsx
> +        <Box>{children}</Box>
nit: I think no need the box here? 🤔

2024-04-03 04:40 UTC, justynoh requested changes
to check with stacey on reordering behavior first!

2024-04-03 04:41 UTC, KenLSM commented
Note: there's a possibility of the submissions being reordered as `lastModified` changes to the latest MRF response time.

2024-05-15 12:55 UTC, KenLSM commented
> Note: there's a possibility of the submissions being **reordered** as lastModified changes to the latest MRF response time.

@staceytan1998 need to get your opinions on the re-ordering behaviour for MRF. For storage mode forms, new submissions doesn't affect existing ordering, but for MRF if we now order by `lastModified` (as opposed to `createdAt`), then the ordering for both CSV and Response Results Page will change. 

-- was reviewing our PRs and noticed this.

2024-05-17 02:34 UTC, staceytan1998 commented
@KenLSM @justynoh is there any way to not reorder for now or is more effort needed to do that? I don't have a good sensing from users as of yet!

2024-05-20 13:07 UTC, KenLSM commented
The reorder is caused by us switching the timestamp that is displayed to the admin from `createdAt` to `lastModified`. If we don't do this, then there will be no reordering.

`createdAt`: timestamp of first submission
`lastModified`: timestamp of latest submission

Lmk if this explanation is not clear.

2024-05-20 13:07 UTC, KenLSM commented
@staceytan1998 The reorder is caused by us switching the timestamp that is displayed to the admin from `createdAt` to `lastModified`. If we don't do this, then there will be no reordering.

`createdAt`: timestamp of first submission
`lastModified`: timestamp of latest submission

Lmk if this explanation is not clear.

2024-09-04 14:05 UTC, KenLSM commented
Closing as we're not getting a good signal from admins on this request.

2024-09-04 14:05 UTC, closed without merging