feat(mrf): multiple static emails
opengovsg/FormSG pull request #7433
Opened 2024-06-24 04:10 UTC by justynoh

## Problem
We want to implement multiple static emails

Closes FRM-1735

## Solution

Enable multiple emails to be added on the frontend. Backend, everything has already been set up previously.

**Breaking Changes** 
- No - this PR is backwards compatible  

## Screenshots
<img width="563" alt="Screenshot 2024-06-24 at 12 04 45 PM" src="https://github.com/opengovsg/FormSG/assets/25571626/f7f4ca5b-cc36-4f43-9355-843c51fdbf29">

<img width="567" alt="Screenshot 2024-06-24 at 12 04 18 PM" src="https://github.com/opengovsg/FormSG/assets/25571626/8b2a95b2-d314-443b-b696-161f3fffae2e">

<img width="559" alt="Screenshot 2024-06-24 at 12 05 00 PM" src="https://github.com/opengovsg/FormSG/assets/25571626/beac582c-917f-4bd1-9ecb-8b761e835231">

<img width="843" alt="Screenshot 2024-06-24 at 12 05 29 PM" src="https://github.com/opengovsg/FormSG/assets/25571626/cbd63b8b-da9d-49b9-a80c-ce465eb68bba">

2024-06-24 15:37 UTC, KenLSM requested changes
One small change request to use `rem`, otherwise LGTM! Thanks for the quick work~

2024-06-24 15:37 UTC, KenLSM commented on frontend/src/features/admin-form/create/workflow/components/WorkflowContent/EditStepBlock/RespondentBlock.tsx
> +            <Text textStyle="body-2" my="8px" py="2px">
```suggestion
            <Text textStyle="body-2" my="0.5rem" py="0.25rem">
```

2024-06-25 01:09 UTC, justynoh commented on frontend/src/features/admin-form/create/workflow/components/WorkflowContent/EditStepBlock/RespondentBlock.tsx
> +            <Text textStyle="body-2" my="8px" py="2px">
done in [0eb778d](https://github.com/opengovsg/FormSG/pull/7433/commits/0eb778d8098a52aee875bf0d398c08c794ea89b6)! soz, forgot the style in forms was to use rem 😓

2024-06-25 02:14 UTC, KenLSM approved these changes

2024-06-25 07:31 UTC, merged