fix: replace trash icon in MRF steps
opengovsg/FormSG pull request #7885
Opened 2024-11-13 03:13 UTC by scottheng96

## Problem
In MRF workflow, blocks have trash icon (top right) giving users ability to delete the step in workflow. For baseline practice in UX, destructive actions should be hidden below the fold 

## Solution
- Replace trash icon with pencil icon
- Update logic upon clicking icon to 'edit step' instead of 'delete step'
- First step has pencil icon now also, since users can't delete the first step, but can edit the first step

## Before & After Screenshots

| Subject | Before | After | 
| ------- | ------- | ----- |
|Trash icon replaced with pencil icon (first step included) |<img width="1147" alt="Screenshot 2024-11-13 at 10 39 57 AM" src="https://github.com/user-attachments/assets/88056fd4-de03-4724-bb9d-96d532c8be8c">|<img width="1127" alt="Screenshot 2024-11-13 at 10 36 47 AM" src="https://github.com/user-attachments/assets/677b493f-dba6-43ac-8f45-f428b66837ca">|
|On click| <img width="1140" alt="Screenshot 2024-11-13 at 11 10 32 AM" src="https://github.com/user-attachments/assets/af4940e0-3000-4154-b874-cce3897b6f4f">| <img width="1139" alt="Screenshot 2024-11-13 at 11 11 11 AM" src="https://github.com/user-attachments/assets/53c1681f-4ac0-4824-8d7d-659a2fe40151">|

2024-11-13 03:39 UTC, KenLSM commented
We can also remove `handleOpenDeleteModal` property from `type InactiveStepBlockProps` as `handleOpenDeleteModal` is no longer referenced in the component.

This also means that we have to cascade the removal of `handleOpenDeleteModal` property on the parent component of `<InactiveStepBlock />`

2024-11-13 09:47 UTC, KenLSM reviewed
LGTM but holding the approval first as I'm getting PM to review the changes in-lieu of Design.

2024-11-14 08:37 UTC, KenLSM commented on frontend/src/features/admin-form/create/workflow/components/WorkflowContent/InactiveStepBlock/InactiveStepBlock.tsx
> +          colorScheme="secondary"
Checked with design, we should be using `primary` instead. We can omit this line since `colorScheme` defaults to `primary` if not defined.

2024-11-14 08:37 UTC, KenLSM requested changes

2024-11-14 08:37 UTC, KenLSM commented on frontend/src/features/admin-form/create/workflow/components/WorkflowContent/InactiveStepBlock/InactiveStepBlock.tsx
> +          colorScheme="secondary"
Checked with design, we should be using primary instead. We can omit this line since colorScheme defaults to primary if not defined.

2024-11-14 08:57 UTC, scottheng96 commented on frontend/src/features/admin-form/create/workflow/components/WorkflowContent/InactiveStepBlock/InactiveStepBlock.tsx
> +          colorScheme="secondary"
Made this change. Pencil is blue-ish now (primary)

2024-11-15 02:00 UTC, KenLSM approved these changes
LGTM!

2024-11-15 02:12 UTC, merged