feat: address field front end work
opengovsg/FormSG pull request #7966
Opened 2024-12-02 10:18 UTC by scottheng96

# DRAFT - checking chromatic PR updates

## Problem

Closes [insert issue #]

## Solution

**Breaking Changes** 

- [ ] Yes - this PR contains breaking changes
    - Details ...
- [ ] No - this PR is backwards compatible  

**Features**:

- Details ...

**Improvements**:

- Details ...

**Bug Fixes**:

- Details ...

## Before & After Screenshots

**BEFORE**:

**AFTER**:

## Tests

## Deploy Notes

**New environment variables**:

- `env var` : env var details

**New scripts**:

- `script` : script details

**New dependencies**:

- `dependency` : dependency details

**New dev dependencies**:

- `dependency` : dependency details

2024-12-20 06:36 UTC, KenLSM commented on frontend/src/features/admin-form/create/constants.ts
> +    isSubmitted: true,
/nit search alias to get input from Ruchel + Kenneth before we release.

2024-12-20 06:37 UTC, KenLSM commented on frontend/src/features/public-form/PublicFormProvider.tsx
> -
Accidental change here? It should be fine to leave a visual break here.

2025-01-09 05:06 UTC, scottheng96 commented on frontend/src/features/admin-form/create/constants.ts
> +    isSubmitted: true,
Added aliases:

  [BasicField.Address]: {
    label: 'Local address',
    icon: SlLocationPin,
    isSubmitted: true,
    searchAliases: [
      'address',
      'location',
      'place',
      'destination',
      'directions',
      'postal code',
      'street',
      'building',
      'road',
      'venue',
    ],
  },
}

2025-01-09 06:06 UTC, scottheng96 commented on frontend/src/features/public-form/PublicFormProvider.tsx
> -
Was accidental! reverting change

2025-02-05 13:22 UTC, KenLSM requested changes
LGTM in general, have suggestions on import references and function flow.

2025-02-05 13:22 UTC, KenLSM commented on __tests__/unit/backend/helpers/generate-form-data.ts
> +    'blockNumber_161',
Note to remove `prefixes_`

2025-02-05 13:22 UTC, KenLSM commented on frontend/src/features/admin-form/responses/IndividualResponsePage/DecryptedRow.tsx
> +    console.log(row)
A stray `console.log` here.

2025-02-05 13:22 UTC, KenLSM commented on frontend/src/features/admin-form/responses/IndividualResponsePage/mutations.ts
> +    if (arr && arr[arr.length - 1])
Would recommend avoiding implicit references. i.e., the last value of the array to be `postal code`.

Perhaps [array destructing](https://www.typescriptlang.org/play/?#code/MYewdgzgLgBAhgJwTAvDA2gKBjARAIwBsRgBrAOQFcBbfAUwQH0BGANmdwBps9oE66UcnGp1GAIQCqAaQCSAFRjiAgvIDy0mAGV5AJQCi+xcw7ccBSgEtCAE0tgA5sNGMuPXIToA3OoSq0GVzM8SjBLIRp6JjdzAAcQaDhCAGEQGzFWAFYABjZTTABdAG5MTFBIWCwcIhIKSIZgvgEhETpg-CtbeydW4M8fP3qEYNDw-yjg+MSUtLbC1HgkErLwCBBPADpiBwAKAG8eGrJxhp4mwWc56s67R0u+718T4Z5RiICXnCmoJNT07gAvgBKIpAA) would be terser here as we would be able to avoid referencing by `arr[n]`

```ts
const arr = [
  "blockNumber_161",
  "streetName_BUKIT BATOK STREET 11",
  "buildingName_",
  "levelNumber_",
  "unitNumber_",
  "postalCode_650161",
];

const [
  blockNumber,
  streetName,
  buildingName,
  levelNumber,
  unitNumber,
  postalCode,
] = arr;

/*
[LOG]: {
  "blockNumber": "blockNumber_161",
  "streetName": "streetName_BUKIT BATOK STREET 11",
  "buildingName": "buildingName_",
  "levelNumber": "levelNumber_",
  "unitNumber": "unitNumber_",
  "postalCode": "postalCode_650161"
} 
*/
```

2025-02-05 13:22 UTC, KenLSM commented on frontend/src/features/admin-form/responses/IndividualResponsePage/mutations.ts
> +      arr.splice(arr.length - 3, 2, combinedUnit)
Generally, we try to avoid in-place modification as it can easily lead to mistakes.

2025-02-05 13:22 UTC, KenLSM commented on frontend/src/features/admin-form/responses/IndividualResponsePage/mutations.ts
> + * ["blockNumber_161","streetName_BUKIT BATOK STREET 11","buildingName_","levelNumber_","unitNumber_","postalCode_650161"]
We can use [`jsdocs`](https://jsdoc.app/tags-param) to annotate input format.

```suggestion
 * @param responses ["blockNumber_161","streetName_BUKIT BATOK STREET 11","buildingName_","levelNumber_","unitNumber_","postalCode_650161"]
```

2025-02-05 13:22 UTC, KenLSM commented on frontend/src/features/admin-form/responses/IndividualResponsePage/mutations.ts
> + * ["blockNumber_161","streetName_BUKIT BATOK STREET 11","buildingName_","levelNumber_","unitNumber_","postalCode_650161"]
We can also annotate [`return`](https://jsdoc.app/tags-returns) values

2025-02-05 13:22 UTC, KenLSM commented on frontend/src/features/admin-form/responses/IndividualResponsePage/mutations.ts
> +    const cleanedArr = arr.filter((item) => item !== '').join(', ')
Taking the above review comments into consideration. Would this suffice?

```ts
const [
  blockNumber,
  streetName,
  buildingName,
  levelNumber,
  unitNumber,
  postalCode,
] = arr;

const formattedLevelUnitNumber = levelNumber && unitNumber ? `#${levelNumber}-${unitNumber}` : [levelNumber, unitNumber]
const formattedPostalCode =  postalCode ? `SINGAPORE ${postalCode}` : postalCode

const formattedFullAddress = [
  blockNumber,
  streetName,
  buildingName,
  formattedLevelUnitNumber,
  formattedPostalCode,
].flat().filter((s) => s !== '').join(', ')

return [formattedFullAddress]
```

2025-02-05 13:22 UTC, KenLSM commented on frontend/src/features/admin-form/responses/ResponsesPage/storage/worker/decryption.worker.ts
> +// if (import.meta.env.NODE_ENV !== 'production') {
Can go ahead and delete L16 through L23.

2025-02-05 13:22 UTC, KenLSM commented on frontend/src/features/public-form/PublicFormService.ts
> +  console.log(formFields)
Note to remove stray logs

2025-02-05 13:22 UTC, KenLSM commented on frontend/src/templates/Field/Address/AddressField.stories.tsx
> +import { useState } from 'react'
Nice. Good to see that we have stories. 👍

2025-02-05 13:22 UTC, KenLSM commented on frontend/src/templates/Field/Address/AddressField.tsx
> +      setIsButtonDisabled(false)
Nice. This was the magic that disabled the button when the postal code wasn't valid.

2025-02-05 13:22 UTC, KenLSM commented on frontend/src/templates/Field/ChildrenCompound/ChildrenCompoundField.tsx
> +    return [childName, ...namesNotSelected(), 'test'].filter((name) => {
Remember to remove stray test data

2025-02-05 13:22 UTC, KenLSM commented on shared/utils/__tests__/address-validation.spec.ts
> +      const mockPostalCode1 = '123456a'
/nit we can also name the test value as what they are. 

```ts
const alphanumericInput = '12345a'
expect(validatePostalCode(alphanumericInput)).toEqual(false)
```

2025-02-05 13:22 UTC, KenLSM commented on src/app/loaders/express/constants.ts
> +    'https://www.onemap.gov.sg/api/common/elastic/search?searchVal=*&returnGeom=Y&getAddrDetails=Y',
We can whitelist a more general API. 

The intention of having this is to protect our users from [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) via unsolicited requests to random sites. (i.e., our web app shouldn't need to call `evil.com` as part of the normal application usage).

Since we do intent to call `onemap.gov.sg` we can have it to be `https://www.onemap.gov.sg/api/` instead.

2025-02-05 13:22 UTC, KenLSM commented on src/app/modules/submission/email-submission/email-submission.util.ts
> + * @returns human-readable format of address, similar to handleAddressResponseDisplay (mutations.ts)
If the function's input and output are the same, could we move them to a shared utils for better reuse?

2025-02-05 13:22 UTC, KenLSM commented on src/app/services/address/address.service.ts
> +      Cookie: '_toffsuid=rB8uPWZEP/wp9bsoBHUZAg==', // check this
We can likely omit this cookie.

2025-02-05 13:22 UTC, KenLSM commented on frontend/src/templates/Field/Address/AddressField.tsx
> +import { verifyAddress } from '../../../../../src/app/services/address/address.service'
FE code should not reference BE code. If there's a need we'll have to move them to `shared`.

Specifically for this function, it should exist as a FE service. We can pair on creating this.

2025-02-05 13:22 UTC, KenLSM commented on src/app/services/address/address.service.ts
> +/**
See comment on `frontend/src/templates/Field/Address/AddressField.tsx` to move this BE service to FE service

2025-02-07 14:01 UTC, scottheng96 commented on __tests__/unit/backend/helpers/generate-form-data.ts
> +    'blockNumber_161',
👍

2025-02-07 14:02 UTC, scottheng96 commented on frontend/src/features/admin-form/responses/IndividualResponsePage/DecryptedRow.tsx
> +    console.log(row)
👍

2025-02-07 14:04 UTC, scottheng96 commented on frontend/src/features/admin-form/responses/IndividualResponsePage/mutations.ts
> + * ["blockNumber_161","streetName_BUKIT BATOK STREET 11","buildingName_","levelNumber_","unitNumber_","postalCode_650161"]
👍

2025-02-07 14:09 UTC, scottheng96 commented on frontend/src/features/admin-form/responses/IndividualResponsePage/mutations.ts
> +    if (arr && arr[arr.length - 1])
that makes more sense. It will not require all the poor arr[x] calls later

2025-02-07 14:09 UTC, scottheng96 commented on frontend/src/features/admin-form/responses/IndividualResponsePage/mutations.ts
> +      arr.splice(arr.length - 3, 2, combinedUnit)
Noted, will stray away from them in future

2025-02-07 14:10 UTC, scottheng96 commented on frontend/src/features/admin-form/responses/IndividualResponsePage/mutations.ts
> +    const cleanedArr = arr.filter((item) => item !== '').join(', ')
Thanks for the improved code change! I'll adopt it

2025-02-07 14:10 UTC, scottheng96 commented on frontend/src/features/admin-form/responses/ResponsesPage/storage/worker/decryption.worker.ts
> +// if (import.meta.env.NODE_ENV !== 'production') {
👍

2025-02-07 14:11 UTC, scottheng96 commented on frontend/src/templates/Field/Address/AddressField.stories.tsx
> +import { useState } from 'react'
👍

2025-02-07 14:12 UTC, scottheng96 commented on frontend/src/templates/Field/Address/AddressField.tsx
> +      setIsButtonDisabled(false)
👍

2025-02-07 14:13 UTC, scottheng96 commented on frontend/src/templates/Field/ChildrenCompound/ChildrenCompoundField.tsx
> +    return [childName, ...namesNotSelected(), 'test'].filter((name) => {
👍

2025-02-07 14:17 UTC, scottheng96 commented on shared/utils/__tests__/address-validation.spec.ts
> +      const mockPostalCode1 = '123456a'
👍 I'll make that change for quality

2025-02-07 14:24 UTC, scottheng96 commented on src/app/loaders/express/constants.ts
> +    'https://www.onemap.gov.sg/api/common/elastic/search?searchVal=*&returnGeom=Y&getAddrDetails=Y',
👍

2025-02-07 14:34 UTC, scottheng96 commented on src/app/modules/submission/email-submission/email-submission.util.ts
> + * @returns human-readable format of address, similar to handleAddressResponseDisplay (mutations.ts)
makes sense. moved it to '~shared/utils/address.ts'

2025-02-07 14:35 UTC, scottheng96 commented on src/app/services/address/address.service.ts
> +      Cookie: '_toffsuid=rB8uPWZEP/wp9bsoBHUZAg==', // check this
👍

2025-02-07 15:09 UTC, scottheng96 commented on src/app/services/address/address.service.ts
> +/**
I have moved it to /frontend/api/oneMap.ts. Let me know if this is an okay or if we have other conventions!

2025-02-07 15:10 UTC, scottheng96 commented on frontend/src/templates/Field/Address/AddressField.tsx
> +import { verifyAddress } from '../../../../../src/app/services/address/address.service'
I have moved it to /frontend/api/oneMap.ts. Let me know if this is an okay or if we have other conventions!

2025-02-09 02:08 UTC, scottheng96 commented on frontend/src/features/admin-form/responses/IndividualResponsePage/mutations.ts
> + * ["blockNumber_161","streetName_BUKIT BATOK STREET 11","buildingName_","levelNumber_","unitNumber_","postalCode_650161"]
added this in the function which i moved to the shared util
```
 * @param responses ["161","BUKIT BATOK STREET 11","","01","02","650161"]
 * @return ["161 BUKIT BATOK STREET 11, #01-02, SINGAPORE 650161"]```

2025-02-09 02:10 UTC, scottheng96 commented on src/app/loaders/express/constants.ts
> +    'https://www.onemap.gov.sg/api/common/elastic/search?searchVal=*&returnGeom=Y&getAddrDetails=Y',
Thanks for the context and suggestion. I'll make that change

2025-02-12 09:42 UTC, KenLSM requested changes

2025-02-12 09:42 UTC, KenLSM commented on frontend/src/api/address.service.ts
Can move it to be under `frontend/src/services/OneMapService.ts`

2025-02-12 09:42 UTC, KenLSM commented on frontend/src/features/public-form/utils/inputTransformation.ts
> +      answerArray.push(`${value}`)
Object.map has an implicit ordering of what `Object.entries` returns may be unexpected. I.e., it could be `[2, 4, 5]` or `[5, 4, 2]` depending on how the object is created[1].


[1] It can be on [property creation time](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in#:~:text=Within%20each%20component%20of%20the%20prototype%20chain%2C%20all%20non%2Dnegative%20integer%20keys%20(those%20that%20can%20be%20array%20indices)%20will%20be%20traversed%20first%20in%20ascending%20order%20by%20value%2C%20then%20other%20string%20keys%20in%20ascending%20chronological%20order%20of%20property%20creation.) which is unexpected for the function caller.

2025-02-12 09:42 UTC, KenLSM commented on frontend/src/features/public-form/utils/inputTransformation.ts
> +      answerArray.push(`${value}`)
Would prefer for us to explicitly list down the array order in answer array

2025-02-12 09:42 UTC, KenLSM commented on src/app/modules/submission/email-submission/email-submission.util.ts
> +    answer: handleAddressResponseDisplay(response.answerArray).join(', '), //TODO Update this
Still need the TODO?

2025-02-12 09:42 UTC, KenLSM commented on src/app/utils/field-validation/index.ts
> +    if (!response.answerArray.every((row) => row.split('_')[1] === '')) {
I recall that we don't have prefixes anymore, is this `_` related to prefixes?

2025-02-12 09:56 UTC, KenLSM commented on src/app/modules/submission/multirespondent-submission/multirespondent-submission.utils.ts
> +          answerArray.push(answerArray.shift() ?? '')
Ordinance problem again for object -> array conversion.

2025-02-12 14:16 UTC, scottheng96 commented on frontend/src/api/address.service.ts
Done!

2025-02-12 14:18 UTC, scottheng96 commented on src/app/modules/submission/email-submission/email-submission.util.ts
> +    answer: handleAddressResponseDisplay(response.answerArray).join(', '), //TODO Update this
removed.

2025-02-12 14:26 UTC, scottheng96 commented on frontend/src/features/public-form/utils/inputTransformation.ts
> +      answerArray.push(`${value}`)
okay fixed this!

2025-02-12 14:29 UTC, scottheng96 commented on src/app/utils/field-validation/index.ts
> +    if (!response.answerArray.every((row) => row.split('_')[1] === '')) {
removed the split since answerArray only handles values now

2025-02-12 14:29 UTC, scottheng96 commented on src/app/modules/submission/multirespondent-submission/multirespondent-submission.utils.ts
> +          answerArray.push(answerArray.shift() ?? '')
fixed this!

2025-02-13 05:15 UTC, KenLSM approved these changes

2025-02-13 05:16 UTC, merged