chore: log errors from concatResponse
opengovsg/FormSG pull request #817
Opened 2020-12-08 03:35 UTC by tshuli

## Problem

Undefined answers are being passed into submission
Part of #808

## Solution
- Not immediately apparent where the validation gap is as unable to replicate
- Propose to log errors from concatResponse first so that we have more details to replicate and debug
- TODO: Review logs in 1 weeks' time

2020-12-08 03:36 UTC, mantariksh commented
conflicts with #755 fyi

2020-12-08 08:00 UTC, liangyuanruo requested changes
the code should return a response after the log statement, otherwise `concatenatedResponse` will continue processing with an undefined value.

2020-12-09 05:02 UTC, mantariksh approved these changes

2020-12-09 05:16 UTC, tshuli commented
@liangyuanruo for approval

2020-12-09 09:15 UTC, liangyuanruo approved these changes

2020-12-09 09:15 UTC, merged