refactor: migrate dropdown validator to ts
opengovsg/FormSG pull request #861
Opened 2020-12-11 14:04 UTC by tshuli

_Blocked by table validator migration_

## Problem
Part of #7

## Solution

**Improvements**

- Migrates dropdown validation to Typescript

## Tests
- [ ] Create two dropdown fields. Hide one of them behind logic.
- [ ] Check that validation on both visible and hidden dropdown fields work when submitting programatically
- Response is rejected if it is not one of the dropdown options

2020-12-15 09:21 UTC, liangyuanruo requested changes
> Blocked by table validator migration

Could we migrate validation for dropdown fields, but leave the table validator to rely on the previous dropdown implementation until we migrate that?

2020-12-21 05:55 UTC, tshuli commented
@liangyuanruo restored the previous dropdown implementation (for TableValidator), for your review

2020-12-21 13:23 UTC, tshuli commented
debugging failed e2e tests for myinfo fields

2020-12-23 06:03 UTC, liangyuanruo requested changes
to address failing tests before approving

2021-02-02 15:25 UTC, liangyuanruo commented on src/app/utils/field-validation/validators/dropdownValidator.ts
> +  const { fieldOptions } = dropdownField
suggest extracting the finding of the correct MyInfo fieldOptions into a separate utility function for reuse, then you can express the logic more succinctly with a ternary op:

```typescript
const validOptions = myInfo?.attr ? getMyInfoOptions(myInfo.attr) : fieldOptions
return isOneOfOptions(validOptions, answer)
  ? right(response)
  : left(`DropdownValidator:\t answer is not a valid dropdown option`)
```

2021-02-02 15:25 UTC, liangyuanruo approved these changes

2021-02-02 15:30 UTC, liangyuanruo commented on src/app/utils/field-validation/validators/dropdownValidator.ts
> +  const { fieldOptions } = dropdownField
more generally, we should always find the correct level of abstraction to achieve clean code. in this example we want to switch between `fieldOptions` depending on whether it is a MyInfo field or not. we don't want a reader of the code to delve into implementation details to find out.

2021-02-03 13:31 UTC, merged